### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by akupervert** [VictorVG/ph#1]
hey.. can you move "reduce working set" to main context menu and underline shortcut key..? i use it a lot

**Comment by VictorVG** [comment]
@akupervert

Sorry, I didn’t immediately see the inc. :( Now the Reduce working set command is available in the Miscleonius - Reduce working set menu and in theory, since it is rarely used, I don’t see the point of transferring it higher personally - it will only bother us.

It is more reasonable to add an accelerator (shortcut) to it for its quick call - for example, Ctrl+Alt+R, but with the letters you need to see which ones are involved in order to avoid their conflict.
