### ISSUE TITLE
ph Crashed

### ISSUE THREAD

**Issue by truefriend-cz** [VictorVG/ph#2]
![image](https://user-images.githubusercontent.com/7845691/88471312-69352500-cf08-11ea-9c29-2afe95dd3f5a.png)
Tested on: https://github.com/VictorVG/ph/releases/tag/v3.0.7753.3226
Windows 10 x64, ENG
Build 2004, 2009 (Beta (19042.388))

**Comment by VictorVG** [comment]
Please, get more info.

Question:

1) Press Minidump button and send me mini dump file %USERPROFILE%\Desktop\PrpcessHacker*.mdmp (~ 1,5 Mb) in to Zip archive as attach.

2) Also from your message did not understand which Process Hacker version you use? If I understand correctly, then you most likely launched PH by unpacking the Zip archive - the installer on Win10 skips the installation of the Security Explorer plugin since he may still cause problems in it, and also selects the version of the Firewall Monitor plugin that is suitable for your OS version.

Try for resolve:

1) Go to menu _Hacker - Plugins..._  and find Firewall Monitor plugin, press right mouse button and press Disable it. Also disable Security Explorer plugin and press Close button for plugins menu.
2) Restart Process Hacker an try use it.
3) Report me your test result's.

Also, try disable Windows Defender - this "antivirus" can spoil any process memory - "_This application is disabled for use - I don't like it!_"

**Comment by VictorVG** [comment]
Please, temporary disable plug-ins by list:

AtomTablePlugin
AvgCpuPlugin
DbgViewPlugin
DnsCachePlugin
DpiAwarenessExtPlugin
FirewallMonitorPlugin
FirmwarePlugin
LiveDumpPlugin
MemoryExtPlugin
NvGpuPlugin
ObjectManagerPlugin
PerfMonPlugin
PoolMonPlugin
ProductPolicyPlugin
ROTViewerPlugin
SecurityExplorerPlugin
ServiceBackupRestorePlugin
SetCriticalPlugin
TaskbarExtPlugin
TerminatorPlugin
TrustedInstallerPlugin
WaitChainPlugin

Notes: today's this plug-ins is incompatible this Windows 10 2004 or newer.

https://github.com/processhacker/plugins-extra/issues/72

**Comment by VictorVG** [comment]
Please, try test v3.0.7764.3237 Git-54430335 - this bug possible fixed in to PH.

**Comment by VictorVG** [comment]
**FIXED**

**Comment by truefriend-cz** [comment]
Sorry, I testet version v3.0.7764.3237 Git-54430335 and newver but problem is stayed.
OS: Windows x64 Pro 19041.388 English - Original Windows version image from Microsoft, and update to 19041.388 build. After update to 19041.388 then get this error.

**Comment by VictorVG** [comment]
Yes, problem is exists, but resolved (?) in to Windows 10.0.1941.421. I reopen this issues

> **Vimann**, Sent: 15: 13 30-07-2020
> 
> Yes, v3.0.7765.3238 Git-f1c3a209 - crashes continue.
> 
> The culprit plugins
> 
> AtomTablePlugin.dll
> AvgCpuPlugin.dll
> DbgViewPlugin.dll
> DnsCachePlugin.dll
> DpiAwarenessExtPlugin.dll
> FirewallMonitorPlugin.dll
> FirmwarePlugin.dll
> LiveDumpPlugin.dll
> MemoryExtPlugin.dll
> NvGpuPlugin.dll
> ObjectManagerPlugin.dll
> PerfMonPlugin.dll
> PoolMonPlugin.dll
> ProductPolicyPlugin.dll
> ROTViewerPlugin.dll
> SecurityExplorer.dll
> ServiceBackupRestorePlugin.dll
> SetCriticalPlugin.dll
> TaskbarExtPlugin.dll
> TerminatorPlugin.dll
> TrustedInstallerPlugin.dll
> WaitChainPlugin.dll
> 
> **KLASS**, Sent: 15: 43 07-30-2020
> 
> Tried it in Hyper-V where Windows 10 Version 2004 is installed (OS Build 19041.264)
> 
> these versions:
> 
> v3.0.7715.3188
> v3.0.7758.3231
> v3.0.7764.3237
> v3.0.7765.3238
> 
> Everyone crashes on startup.
> 
> Dumps.
> 
> **skipik**, Sent: 15: 47 07-30-2020
> 
> Interesting movie. And I have it fixed and does not crash, but the exact OS assembly is 19041.421.

**Comment by VictorVG** [comment]
FIXED?

**Comment by truefriend-cz** [comment]
Yes, thank you for fixed.
